# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meusFilmesClean' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meusFilmesClean
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'meusFilmesCleanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
