//
//  LoginWorker.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 01/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//Criação de protocolo
protocol LoginProtocol {
    func login(_ login: String, password: String, completionHandler: @escaping (UserModel?) -> Void)
}

class LoginWorker
{
    //Inicialização de variavel com o protocolo
    var loginProt: LoginProtocol
    
    //Inicialização do protocolo
    init(_ loginProt: LoginProtocol) {
        self.loginProt = loginProt
    }
    
    func login(_ login: String, password: String, completionHandler: @escaping (UserModel?) -> Void)
    {
        loginProt.login(login, password: password, completionHandler: completionHandler)
    }
}
