//
//  LoginRouter.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 01/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToMeusFilmes(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeToMeusFilmes(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! MeusFilmesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMeusFilmes(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "MeusFilmesViewController") as! MeusFilmesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMeusFilmes(source: dataStore!, destination: &destinationDS)
        }
    }
  
    func passDataToMeusFilmes(source: LoginDataStore, destination: inout MeusFilmesDataStore)
    {
        destination.user = source.user
    }
}
