//
//  LoginInteractor.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 01/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func doLogin(request: Login.User.Request)
}

protocol LoginDataStore
{
    var user: UserModel! { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    var user: UserModel!
  
    func doLogin(request: Login.User.Request) {
        worker = LoginWorker(LoginService())
        worker?.login(request.user, password: request.password) { (response: UserModel?) in
            //Atribui o retorno na variavel que foi definida fora (com base no model)
            self.user = response
            
            let response = Login.User.Response(user: response!)
            self.presenter?.presentMeusFilmes(response: response)
        }
    }
}
