//
//  MeusFilmesInteractor.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 03/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MeusFilmesBusinessLogic
{
    func doSomething(request: MeusFilmes.Something.Request)
}

protocol MeusFilmesDataStore
{
    var user: UserModel! { get set }
}

class MeusFilmesInteractor: MeusFilmesBusinessLogic, MeusFilmesDataStore
{
    var presenter: MeusFilmesPresentationLogic?
    var worker: MeusFilmesWorker?
    var user: UserModel!
    
    // MARK: Do something
    
    func doSomething(request: MeusFilmes.Something.Request)
    {
        worker = MeusFilmesWorker()
        worker?.doSomeWork()
        
        let response = MeusFilmes.Something.Response()
        presenter?.presentSomething(response: response)
    }
}

