//
//  MeusFilmesRouter.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 03/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MeusFilmesRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MeusFilmesDataPassing
{
  var dataStore: MeusFilmesDataStore? { get }
}

class MeusFilmesRouter: NSObject, MeusFilmesRoutingLogic, MeusFilmesDataPassing
{
  weak var viewController: MeusFilmesViewController?
  var dataStore: MeusFilmesDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: MeusFilmesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MeusFilmesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
