//
//  MeusFilmesPresenter.swift
//  meusFilmesClean
//
//  Created by Marcus Titton on 03/10/19.
//  Copyright (c) 2019 Marcus Titton. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MeusFilmesPresentationLogic
{
    func presentSomething(response: MeusFilmes.Something.Response)
}

class MeusFilmesPresenter: MeusFilmesPresentationLogic
{
    weak var viewController: MeusFilmesDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: MeusFilmes.Something.Response)
    {
        let viewModel = MeusFilmes.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

